### PR TITLE
Use generic arch variant and choose kryo385 optmizations during runtime

### PR DESCRIPTION
**Pull request by cryptomilk**

### CODE REVIEW

**Comment by AKoskovich** [comment]
Appears Google did this for P3/XL & P4/XL, but never brought it forward to P5. May have had regressions? P5 never had it as of the first commit so maybe they just forgot to bring it forward.

Also would want to see some sort of benchmark to compare performance impact. I doubt there is really any though. Looks good otherwise though.

**Comment by cryptomilk** [comment]
It is used by other sm8530 devices too, e.g. oneplus

**Comment by cryptomilk** [comment]
Did you manually apply those patches now?

**Comment by AKoskovich** [comment]
> It is used by other sm8530 devices too, e.g. oneplus

Yeah, it originated from Google so was just noting they didn't bring it to P5 which brought up some concerns on using it on modern devices. It's only used on other SM8350 devices because it was inherited from previous SoC trees.



> Did you manually apply those patches now?

Yeah just went ahead and picked them in anyway since I'm leaning towards Google just forgot to bring it forward during P5 bringup. I don't merge pull requests, I dislike "merges" being in trees at all unless its kernel since it screws up rebases if you try to rebase before that point. So this pull request is more or less closed. Prefer code review in general to be in Gerrit instead but repositories aren't in LOS GitHub yet so this is fine.

**Comment by cryptomilk** [comment]
Then do a rebase and commit. You can also disable merges in the settings for doing rebases only.

**Pull request closed without merging**
