### PR TITLE
Allow optional f-droid and use variable for fingerprint and build prop overrides

### PR DESCRIPTION
**Pull request by cryptomilk**
Some fixes, improvements and optional features.

### CODE REVIEW

**Review by AKoskovich — COMMENTED** [review]
IMO this should be made global in vendor/lineage instead of a device specific repository.

**Review by AKoskovich — COMMENTED** [review]
Create vendor/lineage-priv and put your keys inside there, its automatically picked up by vendor/lineage.

https://github.com/LineageOS/android_vendor_lineage/blame/lineage-18.1/config/common.mk#L283

**Review by AKoskovich — COMMENTED** [review]
Disagree on changing model to I006D, its an unfriendly user string. Keep in mind that's the string that is used for stuff like Spotify Connect. "Playing on ZenFone 8" instead of "Playing on I006D".

**Review by AKoskovich — COMMENTED** [review]
This looks good in theory but it won't work without the prior commit with model and stuff so unfortunately nope.

**Comment by cryptomilk** [comment]
Instead of just saying nope, you could ask to change it. Changes done and dropped the cert patch.

**Review by AKoskovich — COMMENTED** [review]
PRODUCT_VERSION and PRODUCT_MODEL_ID aren't used anywhere but here so I'd prefer to just continue hardcoding fingerprint. Build property overrides aren't really changed past bringup so shouldn't be a big deal.

**Comment by cryptomilk** [comment]
If something is used more than once at least, use a variable. Also it is easier to read than searching for it in a long string.

**Review by AKoskovich — COMMENTED** [review]
Please ensure these are sorted alphabetically like before, had them setup that way out of preference. Remove PRODUCT_VERSION from this commit and move it to the overrides/fingerprint commit.

**Review by AKoskovich — COMMENTED** [review]
Move non-AOSP variables directly above PRODUCT_BUILD_PROP_OVERRIDES so its clear they are only being used for that.

**Comment by cryptomilk** [comment]
Done.

**Comment by cryptomilk** [comment]
Rebased to apply to latest changes ...

**Review by AKoskovich — COMMENTED** [review]
Don't swap brand and manufacturer. "Brand" needs to be "asus" to make Play Store happy. I have "Manufacturer"  as "ASUS" so user facing strings appear correct. Otherwise you'll get "asus ZenFone 8" in something like Setup Wizard for example.

Stock has some hacked up stuff to make it work as intended but we want it to all be proper here.

**Comment by cryptomilk** [comment]
Fixed.

**Comment by cryptomilk** [comment]
Right of the merge button should be a down arrow. if you click on it you can rebase and commit. Then it will not create a merge commit.

**Comment by AKoskovich** [comment]
> Right of the merge button should be a down arrow. if you click on it you can rebase and commit. Then it will not create a merge commit.

Didn't know, thanks!

**Pull request closed without merging**
